#include <stdio.h>
#include <stdlib.h>
#include "client.h"

#define TEST    // If I need to test, activate this macro.

static void _test_init_random_input(int *fd)
{
  if ((*fd = open("/dev/random", O_RDONLY)) < 0) {
    printf("[-] Cannot open: /dev/random \n");
    exit(-1);
  }
}

void *client_handler(void *param)
{
  struct client_param *cp = (struct client_param*)param;
  int socket_fd = cp->socket_fd;

  send(socket_fd, &cp->menu, sizeof(cp->menu), 0);
  if (cp->menu == '\x02')
    send(socket_fd, &cp->input, sizeof(cp->input), 0);

  // free(cp);
  pthread_exit(NULL);

  return 0;
}

/*
 * Get a socket fd & Init a socket instance
 * & Make a connection
 *
 * gurantee a socket starting before doing something with thread
 */
void init_client(int *socket_fd, struct sockaddr_in *sock_client)
{
  // TODO: add a setting function fot socket
  // crawling values we need from environments generated by launcher
  *socket_fd = socket(AF_INET, SOCK_STREAM, 0);
  if (*socket_fd == -1) {
    printf("[-] generate socket fd failed\n");
    exit(-1);
  }

  sock_client->sin_family = AF_INET;
  sock_client->sin_addr.s_addr = htonl(INADDR_ANY);
  sock_client->sin_port = htons(8888);

  // Initialize a socket connection
  int conn_status = connect(*socket_fd, (struct sockaddr*)sock_client, sizeof(*sock_client));
  if (conn_status < 0) {
    printf("[-] generate connection of socket failed\n");
    exit(-1);
  }
  printf("[+] Connection estabilished\n");
}

int main()
{
  int socket_fd;
  struct sockaddr_in sock_client;
  pthread_t tid;

  int random_fd;

  // Initializing process
  init_client(&socket_fd, &sock_client);
  _test_init_random_input(&random_fd);

  do {
    char menu;  // 0. EXIT  1. READ  2. WRITE
    int client_request = 0;

    // TEST macro is generated at 'launcher.{h,c}'
#ifdef TEST
    read(random_fd, &menu, sizeof(menu));
    menu = (menu % 2) + 1;

    read(random_fd, &client_request, sizeof(client_request));
#else
    // Clear input buffer
    int c;
    while ((c = getchar()) != '\n' && c != EOF);
    
    scanf("%c", &menu);
    menu -= '0';

    if (menu < 0 || menu > 2) {
      printf("[-] Invalid menu input\n");
      exit(-1);
    }

    if (menu == 0) {
      printf("[[ Bye Bye ]]\n");
      exit(0);
    } else if (menu == 2) { // WRITE condition input
      while ((c = getchar()) != '\n' && c != EOF);
      scanf("%d", &client_request);
    }
#endif /* TEST */

    struct client_param *cparam = (struct client_param*)malloc(sizeof(struct client_param));
    if (!cparam) {
      printf("[-]client_param: malloc failed\n");
      exit(-1);
    }
    cparam->socket_fd = socket_fd;
    cparam->menu = menu;
    cparam->input = client_request;
    
    // Create thread
    // cparam: freed inside the pthread for integrity.
    pthread_create(&tid, NULL, client_handler, cparam);

    sleep(5);

    if (cparam)
      free(cparam);
    cparam = NULL;

    pthread_join(tid, NULL);
  } while(1);

  close(socket_fd);

  return 0;
}
